### ISSUE TITLE
undefined method `join' for nil:NilClass when missing originations in config

### ISSUE THREAD

**Issue by samip5** [neptune-networks/peering#5] opened 2020-08-11 04:00 UTC
I tried to run it with the following config:

```
# The public Autonomous System Number of the border router that this
# configuration is running on.
asn: 213021

# A unique identifer of this router, known as the "router ID". This is often an
# IP address of the border router, as it's thought to be unique.
router_id: '91.221.66.72'

# The ISO 3166-1 country code of where the border router is operating. This is
# used for BGP community support.
region_id: 246  # Finland

# A unique identifer of which physical site of the ASN the border router is
# operating in. This is used for BGP community support.
site_id: 2

# The preferred source address of prefixes learned on export from the Kernel.
# Used in source address selection for outgoing packets. Has to be one of the IP
# addresses of the router. More information can be found in:
# https://bird.network.cz/?get_doc&v=20&f=bird-6.html
preferred_source:
  v4: '91.221.66.72'
  v6: '2a0e:8f02:201a::1'

# The prefixes being originated by this router
originations:
  v6:
    - '2a0e:8f02:201a::/48'
    - '2a0e:8f02:201b::/48'

# The RPKI RTR address and port for dropping RPKI invalids.
rpki:
  host: 'rpki.fqdn.example'
  port: 8282

bgp:
  # Upstreams are BGP sessions that give you a full table and you want to
  # announce your own originations and customer prefixes to.
  upstreams:
    sessions:
      - description: 'Creanova'
        asn: 51765
        local:
          v6: '2a0c:f040:0:5326::2'
        # If the upstream has multiple addresses, you can add many items to the
        # `v4` and `v6` options here.
        remote:
          v6: '2a0c:f040:0:5326::1'
  # A core router session is just an iBGP session (a BGP session where both
  # peers share the same ASN).
  cores:
    sessions:
      - description: 'Turku core'
        asn: 213021
        alias: 'turku-core'
        route_reflector: true
        local:
          v6: 'fd00:169:254:253::1'
        remote:
          v6: 'fd00:169:254:253::2'
```

I'm aware that not all of the values are correct, but I get an error when running `sudo script/generate`:
```
Traceback (most recent call last):
        10: from script/ruby-generate:7:in `<main>'
         9: from script/ruby-generate:7:in `chdir'
         8: from script/ruby-generate:8:in `block in <main>'
         7: from script/ruby-generate:8:in `each'
         6: from script/ruby-generate:11:in `block (2 levels) in <main>'
         5: from script/ruby-generate:11:in `each'
         4: from script/ruby-generate:20:in `block (3 levels) in <main>'
         3: from /peering/lib/generator.rb:15:in `render'
         2: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'
         1: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'
(erb):8:in `block in render': undefined method `join' for nil:NilClass (NoMethodError)
```

**Comment by bswinnerton** [comment] 2020-08-14 20:56
Looks like the problem is in the `originations` section, it's expecting a `v4` key:

```diff
diff --git a/config/test.yml b/config/test.yml
index 374afc3..958f461 100644
--- a/config/test.yml
+++ b/config/test.yml
@@ -24,6 +24,7 @@ preferred_source:

 # The prefixes being originated by this router
 originations:
+  v4: []
   v6:
     - '2a0e:8f02:201a::/48'
     - '2a0e:8f02:201b::/48'
```

Definitely seems like a bug. Even if you add in the empty array there it still will result in a malformed BIRD config (an empty array):

```
define ORIGINATED_PREFIXES_4 = [
  
];

define ORIGINATED_PREFIXES_6 = [
  2a0e:8f02:201a::/48,
  2a0e:8f02:201b::/48
];

define OUR_INTERNAL_PREFIXES_4 = [
  
];

define OUR_INTERNAL_PREFIXES_6 = [
  2a0e:8f02:201a::/48+,
  2a0e:8f02:201b::/48+
];

```

Let me put together something to support missing originations.

**Comment by bswinnerton** [comment] 2020-08-14 21:09
:wave: @samip5, this should now be resolved in the latest version on `master`. Mind giving this another try?

**Closed as completed** 2020-08-14 21:08 UTC
Labels: bug

**Comment by samip5** [comment] 2020-08-15 11:56
@bswinnerton, the actual generation works now, but it still generates for example rules for GLOBAL_BLACKLIST_4, which I think shouldn't be there if you got no IPv4 related things as the config reload will fail due to no GLOBAL_BLACKLIST_4.

Other thing that should also be commented out or not inserted at all are in the function is_own_prefix, as seen here:
https://github.com/neptune-networks/peering/blob/master/templates/bird.conf.erb#L210-L212 and https://github.com/neptune-networks/peering/blob/master/templates/bird.conf.erb#L228-L230. Those will fail with undefined variable errors.
